### ISSUE TITLE
encode/decode messages within messages?

### ISSUE THREAD

**Issue by mitchellwrosen** [alphaHeavy/protobuf#23]
What's the recommended way of deriving `Encode`/`Decode` instances for messages that are built from other messages? The straightforward standalone deriving doesn't quite work, because it requires an `EncodeWire`/`DecodeWire` instance:

```haskell
data Foo = Foo (Required 1 (Value Bar))
  deriving (Generic, Show)
instance Encode Foo -- No instance for EncodeWire Bar

data Bar = Bar (Required 1 (Value Text))
  deriving (Generic, Show)
instance Encode Bar
```

**Comment by NathanHowell** [comment]
I believe you want to use Message instead of Value.

**Comment by mitchellwrosen** [comment]
Oh! Didn't see that =) Thanks!

**Comment by NathanHowell** [comment]
No problem :)
