### ISSUE TITLE
Doesn't compile with GHC 8.8

### ISSUE THREAD

**Issue by HuwCampbell** [alphaHeavy/protobuf#37]
There are calls to `fail` in `Data/ProtocolBuffers/Wire.hs` which don't comport to the MonadFail proposal.

I'm happy to have a look.

**Comment by HuwCampbell** [comment]
Looks like the latest version on hackage (protobuf-0.2.1.2) calls `fail` on `PutM`, but there are more recent commits on Github which would likely fix the issue.

I'd be happy to put up a patch commit over 0.2.1.2 to just fix it there if that's desirable.

**Comment by NathanHowell** [comment]
@HuwCampbell sorry, missed this in a sea of notifications. probably worth backporting, not sure if the breaking changes in 0.3 are worth releasing now

**Comment by HuwCampbell** [comment]
Ok, I'll try to find some time to put a patch together.

**Comment by YoEight** [comment]
Hi,
I got a patch ready based on the tag `v0.2.1.2`: db627d05ef89390b7c5ffcfa901fad99175c1ba8. Could someone upload it to Hackage, I do not belong to the package's maintainer list.

**Comment by NathanHowell** [comment]
@YoEight I've added you as a maintainer to Hackage, release away! 🎉

**Comment by YoEight** [comment]
Thank you very much!

**Comment by YoEight** [comment]
Available on Hackage: https://hackage.haskell.org/package/protobuf-0.2.1.3

**Comment by HuwCampbell** [comment]
Ta
