### ISSUE TITLE
Suspicious amount of time and allocation on decode path

### ISSUE THREAD

**Issue by afcowie** [alphaHeavy/protobuf#4]
I'm not sure if this rings any bells, but we've finally reached the point of doing some profiling on our application and there's one standout: `getVarintPrefixedBS` is doing the bulk of the allocation (fine) but taking an awfully long time to do it.

                                                                                                 individual     inherited
    COST CENTRE                 MODULE                                 no.     entries  %time %alloc   %time %alloc  ticks     bytes 
    getVarintPrefixedBS         Data.ProtocolBuffers.Wire              264           0   77.7   57.8    77.7   57.8   1974 2900040432

Not sure if that rings any bells, but I thought I'd ask and see if there's anything obvious you know about there that we should have a look at.

AfC

**Comment by NathanHowell** [comment]
This is should be fixed by #19, many thanks to @joshbohde.

**Comment by christian-marie** [comment]
Nice, thanks @joshbohde. I might try to re-run my test here and see how much it's improved:
https://github.com/alphaHeavy/protobuf/issues/4#issuecomment-35944192
